### PR TITLE
Move 'shipping_preference' preference under PaypalOrder#to_json

### LINKED ISSUE #133: PayPal SDK JS Error: Disallowed query param: shipping_preference
I had got some issue, with the version 0.3.2 of this gem, in the loading of the PayPal button on the checkout page because the javascript tag was not resolved and got 404. Further investigation got me to found that it was introduced `shipping_preference` but it was set in the wrong place.

In our solidus configuration we sell only digital products and we had disabled 'delivery' step from the checkout flow.

Thanks to the [PayPal](https://developer.paypal.com/docs/api/orders/v2/#definition-order_application_context) docs, `shipping_preference ` should be in the `application_context` under `order` api rest as it is specified.

As say so, I had made a pull request with the correct behavior.

### PR DESCRIPTION
**Pull request by retsef**
Fix #133 shipping_preference with 'NO_SHIPPING' is now provided under PaypalOrder#to_json, otherwise 'SET_PROVIDED_ADDRESS'

### CODE REVIEW

**Comment by retsef** [comment]
Cleanup of #134. @DanielePalombo I tried to cleanup the git history at the best I could.

File: app/models/solidus_paypal_commerce_platform/paypal_order.rb [hunk 1]
```diff
@@ -121,6 +122,18 @@ def price(amount)
...
     end
 
+    def application_context
+      {
+        shipping_preference: require_shipping? ? 'SET_PROVIDED_ADDRESS' : 'NO_SHIPPING'
+      }
+    end
+
+    def require_shipping?
+      step_names = @order ? @order.checkout_steps : ::Spree::Order.checkout_steps.keys
```
Comment (RyanofWoods) [inline app/models/solidus_paypal_commerce_platform/paypal_order.rb:132]: Hi @retsef 👋 
`@order.checkout_steps` returns strings
`::Spree::Order.checkout_steps.keys` returns symbols

Meaning `step_names.include? 'delivery'` will always return false for the latter.

It would also be nice to move `step_names` to another private method:
```ruby
def step_names
  @order ? @order.checkout_steps.map(&:to_sym) : ::Spree::Order.checkout_steps.keys
end
```
And then in another PR we benefit from your method 🙂 
```ruby
    def javascript_sdk_url(order: nil, currency: nil)
      ...
      commit_immediately = step_names.include? "confirm"
```
This would then fix issue #150.

**Review by RyanofWoods — CHANGES_REQUESTED** [review]

**Comment by elia** [comment]
@retsef sorry that stalebot closed this, I reopened and rebased, this is a much needed fix! 🙌

**Review by elia — APPROVED** [review]
🙌 Thanks!
